### YamlMime:Certification
title: 'MCSE: Business Applications'
metadata:
  title: 'MCSE: Business Applications'
  description: 'MCSE: Business Applications'
uid: certification.mcse-business-applications
iconUrl: /media/learn/certification/badges/mcse-badge.svg
summary: |-
  <div>
  <div style='color&#58; red;'><strong>En respuesta a la situación del coronavirus (COVID-19), Microsoft está implementando varios cambios temporales en nuestro programa de capacitación y certificación. <a href='https://www.microsoft.com/en-us/learning/community-blog-post.aspx?BlogId=8&amp;Id=375289'>Aprenda más</a>.</strong><br/><br/></div>
  <div><strong>Esta certificación se retirará el 31de enero de 2021. Ya no podrá conseguir esta certificación después de dicha fecha. Las certificaciones que haya obtenido antes de sus fechas de retirada seguirán apareciendo en su expediente en <a href='https://www.microsoft.com/learning/dashboard.aspx'>Certification Dashboard</a>. Puede también <a href='/learn/certifications/retired-certifications'>explorar todas las certificaciones retiradas</a>.</strong><br/><br/></div>
  </div>

  Esta certificación valida que tiene la experiencia para trabajar y administrar las tecnologías de Microsoft Dynamics 365. Empezará con una base de Microsoft Dynamics 365 y demostrará más experiencia en una o más áreas empresariales específicas.

  Para obtener la certificación MCSE&#58; Business Applications, apruebe uno de los siguientes exámenes&#58;
  - [MB2-716&#58; Microsoft Dynamics 365 Customization and Configuration](/learn/certifications/exams/mb2-716)
  - [MB2-718&#58; Microsoft Dynamics 365 for Customer Service](/learn/certifications/exams/mb2-718)
  - [MB2-719&#58; Microsoft Dynamics 365 for Marketing](/learn/certifications/exams/mb2-719)
  - [MB6-895&#58; Financial Management in Microsoft Dynamics 365 for Finance and Operations](/learn/certifications/exams/mb6-895)
  - [MB6-896&#58; Distribution and Trade in Microsoft Dynamics 365 for Finance and Operations](/learn/certifications/exams/mb6-896)
  - [MB6-897&#58; Microsoft Dynamics 365 for Retail](/learn/certifications/exams/mb6-897)
  - [MB6-898&#58; Microsoft Dynamics 365 for Talent](/learn/certifications/exams/mb6-898)
subTitle: Esta certificación valida que tiene la experiencia para trabajar y administrar las tecnologías de Microsoft Dynamics 365. Empezará con una base de Microsoft Dynamics 365 y demostrará más experiencia en una o más áreas empresariales específicas.
levels:
- beginner
skills:
- ninguno
roles:
- business-analyst
type: mcse
products:
- dynamics
exams:
- uid: exam.mb-2-716
- uid: exam.mb-6-897
- uid: exam.mb-6-898
resources:
- title: Guía de formación y certificación
  description: Estudie todas las certificaciones en una guía concisa de formación y certificaciones.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: Póster de certificación
  description: Consulte una descripción general de los fundamentos, las certificaciones basadas en roles y especialidades.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Exam Replay
  description: Vea dos grandes ofertas para ayudar a aumentar sus probabilidades de éxito.
  href: deals.md
- title: Soporte para certificaciones
  description: Obtener ayuda mediante Foros de soporte de Microsoft Certification. Un moderador de foro responderá en el trascurso de un día hábil, de lunes a viernes.
  href: help.md
- title: Panel de certificación
  description: Revise y administre sus citas programadas, certificados y transcripciones.
  href: https://www.microsoft.com/learning/dashboard.aspx

